# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawdbase < Formula
  desc "Clawdbase CLI — Mission Control for OpenClaw, the managed agent gateway"
  homepage "https://github.com/clawdbase/cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.4/clawdbase_darwin_amd64.tar.gz"
      sha256 "46cb0680fa9f43ea17d51d2155e10e7cfe18af13ac2d83297547e4c00b2f640c"

      define_method(:install) do
        bin.install "clawdbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.4/clawdbase_darwin_arm64.tar.gz"
      sha256 "8ce9de7f0f236e1c51a273633860bf5744cf8f90a5cdbb6d46f90b24012998ec"

      define_method(:install) do
        bin.install "clawdbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.4/clawdbase_linux_amd64.tar.gz"
      sha256 "244f1376bf2629b85d42f54ca59a15834973316dc95e50419d99a176ddb24284"
      define_method(:install) do
        bin.install "clawdbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.4/clawdbase_linux_arm64.tar.gz"
      sha256 "2135a6b4ababdf8f0170dfd076ed83374915ca2ee38f6dcaaa28429a69624076"
      define_method(:install) do
        bin.install "clawdbase"
      end
    end
  end

  test do
    system "#{bin}/clawdbase", "version"
  end
end
