# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawdbase < Formula
  desc "Clawdbase CLI — Mission Control for OpenClaw, the managed agent gateway"
  homepage "https://github.com/clawdbase/cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.2/clawdbase_darwin_amd64.tar.gz"
      sha256 "b00dc147487e119010a0b89767662f3a2e7922304bf5b555423ebb5010acd508"

      define_method(:install) do
        bin.install "clawdbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.2/clawdbase_darwin_arm64.tar.gz"
      sha256 "3f55a70e225af2b832dc2592d8d11b2cbd6812f016b4498bf3726746f7a8940a"

      define_method(:install) do
        bin.install "clawdbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.2/clawdbase_linux_amd64.tar.gz"
      sha256 "cb217c63d775caf806207bdc14ad921d8843e8faad672e96dbb821c963c32254"
      define_method(:install) do
        bin.install "clawdbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clawdbase/cli/releases/download/v0.0.2/clawdbase_linux_arm64.tar.gz"
      sha256 "dc17c6205af593ef032b8e86d980068c0f97e9030abb70cadce1ebf7bbc1d362"
      define_method(:install) do
        bin.install "clawdbase"
      end
    end
  end

  test do
    system "#{bin}/clawdbase", "version"
  end
end
